spring.application.name=section14-api

spring.datasource.url=jdbc:postgresql://localhost:5432/rev_summercamp
spring.datasource.username=postgres
spring.datasource.password=2316841

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect