spring.application.name=section14-api

spring.datasource.url=jdbc:postgresql://localhost:5433/rev_summercampp.backup
spring.datasource.username=postgres
spring.datasource.password=Ishwar10@

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.file.name=logs/rccms.log
logging.level.root=INFO
logging.level.in.gov.rccms=DEBUG